# Generated by Django 4.0.2 on 2022-03-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_session_played_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='player',
        ),
        migrations.DeleteModel(
            name='RoomSession',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
