# Generated by Django 4.0.2 on 2022-03-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_playertransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtransaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'DEPOSIT'), (2, 'WITHDRAWAL')]),
        ),
    ]
