# Generated by Django 4.0.2 on 2022-03-17 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_roomtransaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertransaction',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='roomtransaction',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
