# Generated by Django 4.0.2 on 2022-03-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_playertransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertransaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'ADMIN_TO_PLAYER_GAME'), (2, 'PLAYER_TO_ADMIN_DUTY'), (3, 'ADMIN_TO_PLAYER_SALARY'), (4, 'PLAYER_TO_ADMIN_PROFIT')]),
        ),
    ]
