# Generated by Django 4.0.2 on 2022-04-05 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_player_profit_to_admin'),
        ('transactions', '0006_alter_playertransaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'DEPOSIT'), (2, 'WITHDRAWAL')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.admin')),
            ],
        ),
    ]
