# Generated by Django 4.0.2 on 2022-04-05 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_player_profit_to_admin'),
        ('transactions', '0007_fundtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransaction',
            name='fund',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.fund'),
            preserve_default=False,
        ),
    ]
