# Generated by Django 4.0.2 on 2022-04-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_fundtransaction_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertransaction',
            name='admin_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='playertransaction',
            name='player_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
