# Generated by Django 4.0.2 on 2022-02-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rate',
            field=models.IntegerField(default=40),
        ),
    ]
