# Generated by Django 4.0.2 on 2022-03-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_admin_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='all_time_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='player',
            name='current_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='player',
            name='profit_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='player',
            name='pure_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
