# Generated by Django 4.0.2 on 2022-03-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_player_all_time_profit_player_current_profit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='pure_profit',
            new_name='salary',
        ),
    ]
