# Generated by Django 4.0.2 on 2022-03-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_pure_profit_player_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_profit',
            new_name='admin_profit_share',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='profit_share',
            new_name='self_profit_share',
        ),
    ]
