# Generated by Django 4.0.2 on 2022-03-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_current_profit_player_admin_profit_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='duty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
