# Generated by Django 4.0.2 on 2022-03-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_player_rate'),
        ('rooms', '0004_remove_session_player_delete_roomsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.playerroom')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokersessions.session')),
            ],
        ),
    ]
