# Generated by Django 4.0.2 on 2022-03-17 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokersessions', '0006_alter_session_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
